apiVersion: v1
kind: ReplicationController
metadata:
  name: landingpage
spec:
  replicas: 3
  template:
    metadata:
      labels: 
        app: landingpage
    spec:
      containers:
      - name: landingpage
        image: naokinakao/restapi-02
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080